name: fast-forward
on:
  pull_request:
    types: [opened, reopened. synchronize]
jobs:
  check-fast-forward:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # We appear to need write permission for both pull-requests and
      # issues in order to post a comment to a pull request.
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: nwalfield/sq-git-test/fast-forward@main
